### ISSUE TITLE
Pinned commands

### ISSUE THREAD

**Issue by zcysxy** [RuslanGagushin/Tokyo-Night-Obsidian-Theme#2]
Thanks for your great theme! A small problem: the icons of pinned commands overlap with the text.

![image](https://user-images.githubusercontent.com/48207708/126924634-1a5a6280-926f-474a-aa64-e7639aa9653f.png)

**Comment by zcysxy** [comment]
There are similar problems

![image](https://user-images.githubusercontent.com/48207708/126925922-bfc1ecf1-da19-43c1-bb16-9895c56ebdce.png)

**Comment by RuslanGagushin** [comment]
Hello! 
Thanks for feed back.
Done!
![image](https://user-images.githubusercontent.com/15202306/126955185-360ddb46-0af3-42ad-bfe1-07fbf3783b6b.png)

**Comment by zcysxy** [comment]
Thanks for your rapid fix 🍻! But I think you missed `suggestion-item` in the `suggestion-container`, which was showed in my above comment.

**Comment by RuslanGagushin** [comment]
At what menu i can find this?

**Comment by zcysxy** [comment]
When typing [[wikilinks]], and the left icon is for alias. I found the base element is `suggestion-container`

**Comment by RuslanGagushin** [comment]
![image](https://user-images.githubusercontent.com/15202306/126962880-15b7841b-942b-4f49-ab58-728e606148d0.png)
How i can pinned element here?

**Comment by zcysxy** [comment]
It is not pin. It is alias feature (see [Add aliases to note](https://help.obsidian.md/How+to/Add+aliases+to+note)). Besides, in the default note, non-exist notes also have special icons to their left.

**Comment by RuslanGagushin** [comment]
found, but cant open this item.
Then i click window is closet(
![image](https://user-images.githubusercontent.com/15202306/126964070-f198a454-abdf-41f4-8f5a-b61039348dcb.png)

**Comment by RuslanGagushin** [comment]
Sorry. but i dons know how to find this css

**Comment by zcysxy** [comment]
I think it is `.suggestion-container .suggestion .suggestion-item`. I create a pull request to fix it. You can merge it if you want :)

**Comment by RuslanGagushin** [comment]
its work! great!

**Comment by RuslanGagushin** [comment]
Thank you!

**Comment by zcysxy** [comment]
No problem!
